{{- if .Values.delta.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openbalena.fullname" . }}-delta
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openbalena.labels" . | nindent 4 }}
    app.kubernetes.io/component: delta

    {{- with .Values.delta.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.delta.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.delta.affinity }}
  affinity:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "openbalena.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: delta

      {{- with .Values.delta.labels }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
  replicas: {{ .Values.delta.replicas }}
  template:
    metadata:
      labels:
        {{- include "openbalena.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: delta

        {{- with .Values.delta.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
      - name: {{ .Chart.Name }}-delta
        image: {{ .Values.delta.image.repository }}:{{ .Values.delta.image.tag }}
        imagePullPolicy: {{ .Values.delta.image.pullPolicy }}
        {{- with .Values.delta.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        ports:
          - name: http
            containerPort: 80
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN", "SYS_RESOURCE"]
        env:
        - name: BALENA_TLD
          value: "{{ .Values.global.hostname }}"
        - name: REGISTRY_HOST
          value: "registry.{{ .Values.global.hostname }}"
        - name: DOCKER_HOST
          value: "unix:///var/run/docker.sock"
        - name: DOCKER_BUILDKIT
          value: "0"
        - name: TOKEN_AUTH_BUILDER_TOKEN
          valueFrom:
            secretKeyRef:
              name: openbalena-registry-api-keys
              key: builder
        - name: JWT_ALGO
          value: "ES256"
        volumeMounts:
        - name: balena-engine-storage
          mountPath: /var/lib/balena-engine
        - name: delta-rsync-storage
          mountPath: /delta-rsync
        - name: cert-api
          mountPath: /certs/api
        lifecycle:
          postStart:
            exec:
              command:
                - "sh"
                - "-c"
                - >
                  mkdir /certs/private;
                  ln -s /certs/api/certificate /certs/private/api.{{ .Values.global.hostname }}.pem;
      volumes:
      - name: balena-engine-storage
        emptyDir: {}
      - name: delta-rsync-storage
        emptyDir: {}
      - name: cert-api
        secret:
          secretName: openbalena-pki-api
      {{- with .Values.delta.nodeSelector  }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if or .Values.delta.tolerations .Values.global.tolerations }}
      tolerations:
        {{- if .Values.delta.tolerations }}
        {{- toYaml .Values.delta.tolerations | nindent 8 }}
        {{- end }}
        {{- if .Values.global.tolerations }}
        {{- toYaml .Values.global.tolerations | nindent 8 }}
        {{- end }}
      {{- end }}
{{- end }}
