apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openbalena.fullname" . }}-ui
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openbalena.labels" . | nindent 4 }}
    app.kubernetes.io/component: ui

    {{- with .Values.ui.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.ui.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ui.affinity }}
  affinity:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "openbalena.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: ui

      {{- with .Values.ui.labels }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
  replicas: {{ .Values.ui.replicas }}
  template:
    metadata:
      labels:
        {{- include "openbalena.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: ui

        {{- with .Values.ui.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
      - name: {{ .Chart.Name }}-ui
        image: {{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag }}
        imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
        {{- with .Values.ui.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        ports:
          - name: http
            containerPort: 443
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN", "SYS_RESOURCE"]
        env:
        - name: PORT
          value: "443"
        - name: OPEN_BALENA_JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: openbalena-api-jwt-auth
              key: secret
        - name: OPEN_BALENA_S3_URL
          value: https://s3.{{ .Values.global.hostname }}
        - name: OPEN_BALENA_S3_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: openbalena-s3-keys
              key: access-key
        - name: OPEN_BALENA_S3_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: openbalena-s3-keys
              key: secret-key
        - name: REACT_APP_OPEN_BALENA_UI_URL
          value: https://admin.{{ .Values.global.hostname }}
        - name: REACT_APP_OPEN_BALENA_POSTGREST_URL
          value: https://postgrest.{{ .Values.global.hostname }}
        - name: REACT_APP_OPEN_BALENA_REMOTE_URL
          value: https://remote.{{ .Values.global.hostname }}
        - name: REACT_APP_OPEN_BALENA_API_URL
          value: https://api.{{ .Values.global.hostname }}
        - name: REACT_APP_OPEN_BALENA_API_VERSION
          value: {{ .Values.api.image.tag }}

      {{- with .Values.ui.nodeSelector  }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
