apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openbalena.fullname" . }}-vpn
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openbalena.labels" . | nindent 4 }}
    app.kubernetes.io/component: vpn

    {{- with .Values.vpn.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.vpn.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.vpn.affinity }}
  affinity:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  replicas: {{ .Values.vpn.replicas }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "openbalena.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: vpn

      {{- with .Values.vpn.labels }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
  template:
    metadata:
      labels:
        {{- include "openbalena.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: vpn

        {{- with .Values.vpn.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
      - name: {{ .Chart.Name }}-vpn
        image: {{ .Values.vpn.image.repository }}:{{ .Values.vpn.image.tag }}
        imagePullPolicy: {{ .Values.vpn.image.pullPolicy }}
        {{- with .Values.vpn.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        ports:
        - name: vpn
          containerPort: 443
        - name: tunnel
          containerPort: 3128
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN", "SYS_RESOURCE", "NET_ADMIN"]
        env:
        - name: CONFD_BACKEND
          value: "ENV"
        - name: API_SERVICE_API_KEY
          valueFrom:
            secretKeyRef:
              name: openbalena-vpn-api-keys
              key: api
        - name: API_HOST
          value: "api.{{ .Values.global.hostname }}"
        - name: ROOT_CA
          valueFrom:
            secretKeyRef:
              name: openbalena-cert-root
              key: ca
        - name: VPN_PORT
          value: "443"
        - name: PRODUCTION_MODE
          value: "{{ index .Values "global" "production-mode" }}"
        - name: VPN_GATEWAY
          value: "10.2.0.1"
        - name: SENTRY_DSN
          value: "{{ index .Values "vpn" "sentry-dsn" }}"
        - name: VPN_HAPROXY_USEPROXYPROTOCOL
          value: "false"
        - name: VPN_OPENVPN_CA_CRT
          valueFrom:
            secretKeyRef:
              name: openbalena-cert-vpn
              key: ca
        - name: VPN_OPENVPN_SERVER_CRT
          valueFrom:
            secretKeyRef:
              name: openbalena-cert-vpn
              key: crt
        - name: VPN_OPENVPN_SERVER_DH
          valueFrom:
            secretKeyRef:
              name: openbalena-vpn-auth
              key: dh-params
        - name: VPN_OPENVPN_SERVER_KEY
          valueFrom:
            secretKeyRef:
              name: openbalena-cert-vpn
              key: key
        - name: VPN_SERVICE_API_KEY
          valueFrom:
            secretKeyRef:
              name: openbalena-api-keys
              key: vpn

        # Use the 'eth0' interface, so the VPN will register itself via the Cluster IP of the pod
        - name: VPN_SERVICE_REGISTER_INTERFACE
          value: "eth0"
        volumeMounts:
        - mountPath: /run
          name: run
        - mountPath: /sys/fs/cgroup
          name: cgroup
        - mountPath: /etc/podinfo
          name: podinfo
        - mountPath: /balena
          name: balena
        lifecycle:
          postStart:
            exec:
              command: ["touch", "/balena/.env"]
      volumes:
      - name: run
        emptyDir:
          medium: Memory
      - name: cgroup
        emptyDir:
          medium: Memory
      - name: podinfo
        downwardAPI:
          items:
          - path: "cpu_request"
            resourceFieldRef:
              containerName: {{ .Chart.Name }}-vpn
              resource: requests.cpu
      - name: balena
        emptyDir:
          medium: Memory

      {{- with .Values.vpn.nodeSelector  }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
