{{- if .Values.issuers.acme.enabled }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Values.issuers.acme.name }}
  namespace: {{ .Release.Namespace }}
spec:
  acme:
    server: {{ .Values.issuers.acme.server }}
    email: {{ .Values.issuers.acme.email }}
    privateKeySecretRef:
      name: openbalena-tls-certificate
    solvers:
    - http01:
        ingress:
          class: {{ .Values.haproxy.controller.ingressClass }}
          podTemplate:
            spec:
              {{- with .Values.issuers.acme.nodeSelector }}
              nodeSelector:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              {{- if or .Values.issuers.acme.tolerations .Values.global.tolerations }}
              tolerations:
                {{- if .Values.issuers.acme.tolerations }}
                {{- toYaml .Values.issuers.acme.tolerations | nindent 16 }}
                {{- end }}
                {{- if .Values.global.tolerations }}
                {{- toYaml .Values.global.tolerations | nindent 16 }}
                {{- end }}
              {{- end }}
{{- end }}