{{- if .Values.issuers.acme.enabled }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Values.issuers.acme.name }}
  namespace: {{ .Release.Namespace }}
spec:
  acme:
    server: {{ .Values.issuers.acme.server }}
    email: {{ .Values.issuers.acme.email }}
    privateKeySecretRef:
      name: openbalena-certificate-key
    solvers:
    - http01:
        ingress:
          class: {{ .Values.haproxy.controller.ingressClass }}
          podTemplate:
            spec:
              {{- with .Values.issuers.acme.nodeSelector  }}
              nodeSelector:
                {{- toYaml . | nindent 16 }}
              {{- end }}
{{- end }}