apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "openbalena.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openbalena.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.ingress.http.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  tls:
  - hosts:
    - {{ .Values.global.hostname }}
    - api.{{ .Values.global.hostname }}
    - registry.{{ .Values.global.hostname }}
    - admin.{{ .Values.global.hostname }}
    - postgrest.{{ .Values.global.hostname }}
    - remote.{{ .Values.global.hostname }}
    {{- if .Values.s3.enabled }}
    - s3.{{ .Values.global.hostname }}
    {{- end }}
    {{- if .Values.builder.enabled }}
    - builder.{{ .Values.global.hostname }}
    {{- end }}
    {{- if .Values.delta.enabled }}
    - delta.{{ .Values.global.hostname }}
    {{- end }}
    secretName: {{ include "openbalena.fullname" . }}-tls
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  rules:
  - host: api.{{ .Values.global.hostname }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "openbalena.fullname" . }}-api
            port:
              number: 80
      {{- if .Values.helper.enabled }}
      - path: /download
        pathType: Prefix
        backend:
          service:
            name: {{ include "openbalena.fullname" . }}-helper
            port:
              number: 80
      - path: /v6/supervisor_release
        pathType: Prefix
        backend:
          service:
            name: {{ include "openbalena.fullname" . }}-helper
            port:
              number: 80
      {{- end }}
  - host: registry.{{ .Values.global.hostname }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "openbalena.fullname" . }}-registry
            port:
              number: 80
  {{- if .Values.s3.enabled }}
  - host: s3.{{ .Values.global.hostname }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "openbalena.fullname" . }}-s3
            port:
              number: 80
  {{- end }}
  - host: admin.{{ .Values.global.hostname }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ include "openbalena.fullname" . }}-ui
            port:
              number: 80
  - host: postgrest.{{ .Values.global.hostname }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ include "openbalena.fullname" . }}-postgrest
            port:
              number: 80
  - host: remote.{{ .Values.global.hostname }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ include "openbalena.fullname" . }}-remote
            port:
              number: 80
  {{- if .Values.builder.enabled }}
  - host: builder.{{ .Values.global.hostname }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "openbalena.fullname" . }}-builder
            port:
              number: 80
  {{- end }}
  {{- if .Values.delta.enabled }}
  - host: delta.{{ .Values.global.hostname }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "openbalena.fullname" . }}-delta
            port:
              number: 80
  {{- end }}
