{{- if .Values.builder.arm64.persistence.enabled }}
{{- $pvc := lookup "v1" "PersistentVolumeClaim" .Release.Namespace "builder-arm64-pvc" }}
{{- if not $pvc }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: builder-arm64-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: builder-arm64
  {{- if .Values.builder.arm64.persistence.retainOnDelete }}
  annotations:
    "helm.sh/resource-policy": keep
  {{- end }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.builder.arm64.persistence.size }}
  {{- if .Values.builder.arm64.persistence.storageClass }}
  storageClassName: {{ .Values.builder.arm64.persistence.storageClass }}
  {{- end }}
{{- end }}
{{- end }}