{{ if .Values.secrets.create }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: openbalena-cert-root
  namespace: {{ .Release.Namespace }}
stringData:
  ca: {{ index .Values "global" certificates.root.ca | quote }}
  crt: {{ index .Values "global" certificates.root.crt | quote }}
  key: {{ index .Values "global" certificates.root.key | quote }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: openbalena-cert-jwt
  namespace: {{ .Release.Namespace }}
stringData:
  crt: {{ index .Values "global" "keys" "token-auth-pub" | quote }}
  key: {{ index .Values "global" "keys" "token-auth-key" | quote }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: openbalena-cert-vpn
  namespace: {{ .Release.Namespace }}
stringData:
  ca: {{ index .Values "global" "certificates" "vpn" "ca-chain" | quote }}
  crt: {{ index .Values "global" "certificates" "vpn" "crt" | quote }}
  key: {{ index .Values "global" "certificates" "vpn" "server-key" | quote }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: openbalena-api-creds
  namespace: {{ .Release.Namespace }}
stringData:
  email: {{ index .Values "global" "email" }}
  password: {{ index .Values "global" "password" | quote }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: openbalena-api-keys
  namespace: {{ .Release.Namespace }}
stringData:
  vpn: {{ index .Values "global" "keys" "service-api-key" | quote }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: openbalena-api-cookie-session
  namespace: {{ .Release.Namespace }}
stringData:
  secret: {{ index .Values "global" "keys" "cookie-secret" | quote }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: openbalena-api-jwt-auth
  namespace: {{ .Release.Namespace }}
stringData:
  secret: {{ index .Values "global" "keys" "jwt-secret" | quote }}
  keyid: {{ index .Values "global" "keys" "token-auth-kid" | quote }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: openbalena-vpn-auth
  namespace: {{ .Release.Namespace }}
stringData:
  dh-params: {{ index .Values "global" "certificates" "vpn" "dh" | quote }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: openbalena-vpn-api-keys
  namespace: {{ .Release.Namespace }}
stringData:
  api: {{ index .Values "global" "keys" "api-vpn-service-api-key" | quote }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: openbalena-registry-api-keys
  namespace: {{ .Release.Namespace }}
stringData:
  builder: {{ index .Values "global" "keys" "token-auth-builder-token" | quote }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: openbalena-s3-keys
  namespace: {{ .Release.Namespace }}
stringData:
  access-key: {{ index .Values "global" "s3" "accesskey" | quote }}
  secret-key: {{ index .Values "global" "s3" "secretkey" | quote }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: openbalena-db-creds
  namespace: {{ .Release.Namespace }}
stringData:
  username: {{ index .Values "global" "db" "user" | quote }}
  password: {{ index .Values "global" "db" "password" | quote }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: openbalena-registry-http
  namespace: {{ .Release.Namespace }}
stringData:
  secret: {{ index .Values "global" "keys" "registry-secret-key" | quote }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: openbalena-ssh
  namespace: {{ .Release.Namespace }}
stringData:
  authorized-keys: {{ index .Values "global" "ssh-authorized-keys" | quote }}
{{ end }}