{{ if .Values.secrets.create }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: openbalena-api-creds
  namespace: {{ .Release.Namespace }}
stringData:
  email: {{ index .Values "global" "email" | quote }}
  password: {{ index .Values "global" "password" | quote }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: openbalena-api-keys
  namespace: {{ .Release.Namespace }}
stringData:
  vpn: {{ index .Values "global" "keys" "service-api-key" | quote }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: openbalena-api-cookie-session
  namespace: {{ .Release.Namespace }}
stringData:
  secret: {{ index .Values "global" "keys" "cookie-secret" | quote }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: openbalena-api-jwt-auth
  namespace: {{ .Release.Namespace }}
stringData:
  secret: {{ index .Values "global" "keys" "jwt-secret" | quote }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: openbalena-api-github-auth
  namespace: {{ .Release.Namespace }}
stringData:
  token: {{ index .Values "api" "contractsPrivateRepoToken" | quote }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: openbalena-vpn-api-keys
  namespace: {{ .Release.Namespace }}
stringData:
  api: {{ index .Values "global" "keys" "api-vpn-service-api-key" | quote }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: openbalena-registry-api-keys
  namespace: {{ .Release.Namespace }}
stringData:
  builder: {{ index .Values "global" "keys" "token-auth-builder-token" | quote }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: openbalena-s3-keys
  namespace: {{ .Release.Namespace }}
stringData:
  access-key: {{ index .Values "global" "s3" "accesskey" | quote }}
  secret-key: {{ index .Values "global" "s3" "secretkey" | quote }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: openbalena-db-creds
  namespace: {{ .Release.Namespace }}
stringData:
  username: {{ index .Values "global" "db" "user" | quote }}
  password: {{ index .Values "global" "db" "password" | quote }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: openbalena-registry-http
  namespace: {{ .Release.Namespace }}
stringData:
  secret: {{ index .Values "global" "keys" "registry-secret-key" | quote }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: openbalena-ssh
  namespace: {{ .Release.Namespace }}
stringData:
  authorized-keys: {{ index .Values "global" "ssh-authorized-keys" | quote }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: openbalena-pki-root
  namespace: {{ .Release.Namespace }}
stringData:
  ca_chain: |+
{{ .Files.Get "certs/root-ca.crt" | indent 4 }}
  issuing_ca: |+
{{ .Files.Get "certs/root-ca.crt" | indent 4 }}
  certificate: |+
{{ .Files.Get "certs/root-cert.crt" | indent 4 }}
  private_key: |+
{{ .Files.Get "certs/root-cert.key" | indent 4 }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: openbalena-pki-api
  namespace: {{ .Release.Namespace }}
stringData:
  certificate: |+
{{ .Files.Get "certs/api-cert.crt" | indent 4 }}
  private_key: |+
{{ .Files.Get "certs/api-cert.key" | indent 4 }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: openbalena-pki-vpn
  namespace: {{ .Release.Namespace }}
stringData:
  ca_chain: |+
{{ .Files.Get "certs/vpn-ca.crt" | indent 4 }}
  issuing_ca: |+
{{ .Files.Get "certs/vpn-ca.crt" | indent 4 }}
  certificate: |+
{{ .Files.Get "certs/vpn-cert.crt" | indent 4 }}
  private_key: |+
{{ .Files.Get "certs/vpn-cert.key" | indent 4 }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: openbalena-vpn-dhparams
  namespace: {{ .Release.Namespace }}
stringData:
  dhparams: |+
{{ .Files.Get "certs/vpn-dh.pem" | indent 4 }}
{{ end }}