{{ if .Values.secrets.create }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: openbalena-cert-root
  namespace: {{ .Release.Namespace }}
stringData:
  ca: {{ .Values.global.certificates.root.ca }}
  crt: {{ .Values.global.certificates.root.crt }}
  key: {{ .Values.global.certificates.root.key }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: openbalena-cert-jwt
  namespace: {{ .Release.Namespace }}
stringData:
  crt: {{ ".Values.global.keys.token-auth-pub" }}
  key: {{ ".Values.global.keys.token-auth-key" }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: openbalena-cert-vpn
  namespace: {{ .Release.Namespace }}
stringData:
  ca: {{ ".Values.global.certificates.vpn.ca-chain" }}
  crt: {{ .Values.global.certificates.vpn.crt }}
  key: {{ ".Values.global.certificates.vpn.server-key" }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: openbalena-api-creds
  namespace: {{ .Release.Namespace }}
stringData:
  email: {{ .Values.global.email }}
  password: {{ .Values.global.password }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: openbalena-api-keys
  namespace: {{ .Release.Namespace }}
stringData:
  vpn: {{ ".Values.global.keys.service-api-key" }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: openbalena-api-cookie-session
  namespace: {{ .Release.Namespace }}
stringData:
  secret: {{ ".Values.global.keys.cookie-secret" }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: openbalena-api-jwt-auth
  namespace: {{ .Release.Namespace }}
stringData:
  secret: {{ ".Values.global.keys.jwt-secret" }}
  keyid: {{ ".Values.global.keys.token-auth-kid" }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: openbalena-vpn-auth
  namespace: {{ .Release.Namespace }}
stringData:
  dh-params: {{ .Values.global.certificates.vpn.dh }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: openbalena-vpn-api-keys
  namespace: {{ .Release.Namespace }}
stringData:
  api: {{ ".Values.global.keys.api-vpn-service-api-key" }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: openbalena-registry-api-keys
  namespace: {{ .Release.Namespace }}
stringData:
  builder: {{ ".Values.global.keys.token-auth-builder-token" }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: openbalena-s3-keys
  namespace: {{ .Release.Namespace }}
stringData:
  access-key: {{ .Values.global.s3.accesskey }}
  secret-key: {{ .Values.global.s3.secretkey }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: openbalena-db-creds
  namespace: {{ .Release.Namespace }}
stringData:
  username: {{ .Values.global.db.user }}
  password: {{ .Values.global.db.password }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: openbalena-registry-http
  namespace: {{ .Release.Namespace }}
stringData:
  secret: {{ ".Values.global.keys.registry-secret-key" }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: openbalena-ssh
  namespace: {{ .Release.Namespace }}
stringData:
  authorized-keys: {{ ".Values.global.ssh-authorized-keys" }}
{{ end }}