{{- if .Values.s3.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "openbalena.fullname" . }}-s3
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openbalena.labels" . | nindent 4 }}
    app.kubernetes.io/component: s3

    {{- with .Values.s3.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.s3.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.s3.affinity }}
  affinity:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  serviceName: {{ include "openbalena.fullname" . }}-s3
  selector:
    matchLabels:
      {{- include "openbalena.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: s3

      {{- with .Values.s3.labels }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
  replicas: {{ .Values.s3.replicas }}
  template:
    metadata:
      labels:
        {{- include "openbalena.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: s3

        {{- with .Values.s3.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      initContainers:
      - name: wait-for-promtail
        image: busybox:latest
        command:
        - /bin/sh
        - -c
        - >
          until nc -vz {{ .Values.global.promtail.server }} {{ .Values.global.promtail.port }};
            do echo "Waiting for {{ .Values.global.promtail.server }}:{{ .Values.global.promtail.port }}";
            sleep 1;
          done
      containers:
      - name: {{ .Chart.Name }}-s3
        image: {{ .Values.s3.image.repository }}:{{ .Values.s3.image.tag }}
        imagePullPolicy: {{ .Values.s3.image.pullPolicy }}
        {{- with .Values.s3.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        ports:
          - name: http
            containerPort: 80
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN", "SYS_RESOURCE"]
        env:
        - name: CONFD_BACKEND
          value: "ENV"
        - name: S3_MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: openbalena-s3-keys
              key: access-key
        - name: S3_MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: openbalena-s3-keys
              key: secret-key
        - name: BUCKETS
          value: "{{ index .Values "global" "s3" "buckets" }}"
        volumeMounts:
        - mountPath: /export
          name: data
        - mountPath: /run
          name: run
        - mountPath: /sys/fs/cgroup
          name: cgroup
        - mountPath: /balena
          name: balena
        lifecycle:
          postStart:
            exec:
              command:
                - "sh"
                - "-c"
                - >
                  mkdir /balena;
                  touch /balena/{{ .Values.global.hostname }}.env;
                  mkdir /certs/private;
                  ln -s /certs/vpn/issuing_ca /certs/ca-bundle.pem;
                  ln -s /certs/vpn/certificate /certs/private/vpn.{{ .Values.global.hostname }}.pem;
                  ln -s /certs/vpn/private_key /certs/private/vpn.{{ .Values.global.hostname }}.key;
                  ln -s /certs/vpn-dhparams/dhparams /certs/private/dhparam.{{ .Values.global.hostname }}.pem;
                  ln -s /certs/api/certificate /certs/private/api.{{ .Values.global.hostname }}.pem;
                  ln -s /certs/api/private_key /certs/private/api.{{ .Values.global.hostname }}.key;
                  ln -s /certs/api-kid/api_kid /certs/private/api.{{ .Values.global.hostname }}.kid;
                  echo 'module(load="imjournal")\nmodule(load="mmjsonparse")\n$imjournalRatelimitInterval 0\n$imjournalRatelimitBurst 0\n*.* action(type="omfwd" Target="openbalena-promtail-syslog" Port="1514" Protocol="tcp" Template="RSYSLOG_SyslogProtocol23Format" TCP_Framing="octet-counted")' > /etc/rsyslog.d/00-promtail-relay.conf;
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: data
      - name: run
        emptyDir:
          medium: Memory
      - name: cgroup
        emptyDir:
          medium: Memory
      - name: balena
        emptyDir:
          medium: Memory

      {{- with .Values.s3.nodeSelector  }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      {{- if .Values.s3.storageClass }}
      storageClassName: {{ .Values.s3.storageClass }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.s3.storage }}
{{- end }}
