apiVersion: v1
kind: Service
metadata:
  name: {{ include "openbalena.fullname" . }}-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openbalena.labels" . | nindent 4 }}
    app.kubernetes.io/component: api

    {{- with .Values.api.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    haproxy.org/backend-config-snippet: |
      timeout connect 0ms
      timeout client 0ms
      timeout server 0ms
      timeout http-keep-alive 0ms
      timeout http-request 0ms

    {{- with .Values.api.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    {{- include "openbalena.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api

    {{- with .Values.api.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  {{- with .Values.api.service.externalIPs }}
  externalIPs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
