apiVersion: v2
name: openbalena
description: openBalena kubernetes Chart
type: application
version: 1.1.2
appVersion: v3.4.3
keywords:
- balena
- openbalena
maintainers:
- name: bartversluijs
  email: bartv@nexelit.io
- name: David Caputo
  email: dcaputo@harmoni.io

dependencies:
- name: haproxy-ingress
  version: 0.14.2
  alias: haproxy
  repository: "https://haproxy-ingress.github.io/charts"
- name: loki
  version: 5.35.0
  alias: loki
  repository: "https://grafana.github.io/helm-charts"
